"""Add location fields

Revision ID: 53ea46d1f947
Revises: d3c27e947e18
Create Date: 2020-10-25 21:58:58.055054

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "53ea46d1f947"
down_revision = "d3c27e947e18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("humans", sa.Column("country_code", sa.String(), nullable=True))
    op.add_column("humans", sa.Column("lat", sa.String(), nullable=True))
    op.add_column("humans", sa.Column("lng", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("humans", "lng")
    op.drop_column("humans", "lat")
    op.drop_column("humans", "country_code")
    # ### end Alembic commands ###
